[package]
name = "rust_job_search"
version = "0.1.0"
edition = "2024"

[dependencies]
refinery = { version = "0.9.0", features = ["rusqlite-bundled"] }
rusqlite = { version = "0.37.0", features = ["bundled", "chrono", "url"] }
url = "2.5.7"
